### ISSUE TITLE
OS name for ARM64 macOS in 'rules' field in org.lwjgl3.json is incorrect

### ISSUE THREAD

**Issue by chipgeekjr** [CleanroomMC/CleanroomMMC#6]
Title, correct name is "osx-arm64", as used in net.minecraft.json.

**Comment by KorewaLidesu** [comment]
Which launcher are you using?

**Comment by chipgeekjr** [comment]
Prism 8.0, on an M1 mac.

**Comment by KorewaLidesu** [comment]
Prism/PolyMC is not really support for now due to a small change in their internal for meta handling unlike MultiMC.
I will rework on this once free time. For now just edit the rules.

**Comment by KorewaLidesu** [comment]
Fixed in https://github.com/CleanroomMC/CleanroomMMC/commit/4d9ad14912e7c4ffe54a62b7f9d94169984941b9
