### ISSUE TITLE
M1macOS can't start

### ISSUE THREAD

**Issue by bakemann** [CleanroomMC/CleanroomMMC#7]
I use M1mac.
Can't start with arm java, see log1 file.
Also can't start with x64 java, see log2 file.
[log1.log](https://github.com/CleanroomMC/CleanroomMMC/files/14550309/log1.log)
[log2.log](https://github.com/CleanroomMC/CleanroomMMC/files/14550313/log2.log)

**Comment by KorewaLidesu** [comment]
Reopened as tracking issue.

**Comment by sassa7777** [comment]
is this still working on?

**Comment by KorewaLidesu** [comment]
Fixed in https://github.com/CleanroomMC/CleanroomMMC/commit/4d9ad14912e7c4ffe54a62b7f9d94169984941b9
