### ISSUE TITLE
0.2.2-alpha+build.20.run.660 Can't start because of wrong name

### ISSUE THREAD

**Issue by superDoubleXZ** [CleanroomMC/CleanroomMMC#8]
When I try to start it, I get the following error

Instance update failed because: Some artifacts marked as 'local' are missing their files:
/instances/Cleanroom_MMC 0.2.2-alpha-build.20.run.660/libraries/cleanroom-0.2.2-alpha+build.20.run.660-universal.jar

But the name of the file under /libraries is: 
cleanroom-0.2.2-alpha-build.20.run.660-universal.jar

The problem is the symbols after the "alpha", one is “+“ and the other is ”-“.

**Comment by kappa-maintainer** [comment]
Use Prism 8.4 and reimport the pack. That's a dumb bug in 8.3 or older

**Comment by Oregano1963** [comment]
this should probably be closed. Prism fixed the issue
